In [5]:
from _utils import parse_solution_overview

baseline_data = parse_solution_overview("./00_baseline_data.zip")
baseline_data = baseline_data.drop_duplicates(subset=["Instance", "AlgorithmID", "AlgorithmIteration", "ModelID", "Settings"])
baseline_data.loc[baseline_data["Path"].isna(), "SampleSize"] = None
baseline_data = baseline_data[["Instance", "#Variables", "#Clauses", "Algorithm", "Settings", "Time", "SampleSize", "Path"]]
baseline_data.rename(columns={"Time(s)": "runtime", "#Variables": "num_vars", "#Clauses": "num_clauses", "Instance": "instance_name", "Path": "path_to_baseline_sample", "Algorithm": "baseline_alg", "Settings": "baseline_alg_conf", "SampleSize": "sample_size"}, inplace=True)
baseline_data.to_json("./00_simple_baseline_data.json.zip")
baseline_data

Found the data folders: {'results/2023-07-16_22-29-39/'}

,instance_name,num_vars,num_clauses,baseline_alg,baseline_alg_conf,Time,sample_size,path_to_baseline_sample
0,calculate,9,15,ACTS-IPOG-FT,t2,878,9.0,results/2023-07-16_22-29-39/1_1_0_1_sample.csv
1,lcm,9,16,ACTS-IPOG-FT,t2,484,9.0,results/2023-07-16_22-29-39/2_1_0_1_sample.csv
2,email,10,17,ACTS-IPOG-FT,t2,478,8.0,results/2023-07-16_22-29-39/3_1_0_1_sample.csv
3,ChatClient,14,20,ACTS-IPOG-FT,t2,509,10.0,results/2023-07-16_22-29-39/4_1_0_1_sample.csv
4,car,16,33,ACTS-IPOG-FT,t2,556,6.0,results/2023-07-16_22-29-39/5_1_0_1_sample.csv
...,...,...,...,...,...,...,...,...
507,m5272c3,1336,3111,ACTS-IPOF-CSP,t2,900030,NaN,None
508,sam7ex256,1345,3155,ACTS-IPOF-CSP,t2,900028,NaN,None
509,phycore229x,1373,3185,ACTS-IPOF-CSP,t2,900032,NaN,None
510,FreeBSD-8_0_0,1397,15692,ACTS-IPOF-CSP,t2,900009,NaN,None
511,ea2468,1408,3319,ACTS-IPOF-CSP,t2,900037,NaN,None

In [6]:
import pandas as pd

lower_bound_data = pd.read_json("../04_based_on_yasa/out/07_best_lower_bounds.json.zip")
lower_bound_data

                  instance_name  best_lower_bound
0                           APL                 7
1                     APL-Model                 7
2               BankingSoftware                28
3                 BattleofTanks               256
4                    ChatClient                 7
5                          DMIE                16
6                        E-Shop                 8
7                    EMBToolkit              1851
8                        FameDB                 8
9                    FeatureIDE                 7
10                FreeBSD-8_0_0                29
11                          PPU                12
12                     SafeBali                11
13                  SortingLine                 9
14                     TightVNC                 8
15                       Violet                15
16            WaterlooGenerated                82
17                     XSEngine                32
18                     aaed2000                51
19                     am31_sim                28
20             atlas_mips32_4kc                31
21                        axTLS                10
22                  berkeleyDB1                15
23                  berkeleyDB2                11
24               busybox-1_18_0                12
25               busybox-1_29_2                18
26  busybox_2007-01-24_09-14-09                21
27  busybox_2020-12-16_21-53-05                18
28                    calculate                 5
29                          car                 5
30                         dell                31
31              eCos-3-0_i386pc                33
32                       ea2468                31
33                        email                 6
34   fiasco_2017-09-26_11-30-56               225
35   fiasco_2020-12-01_14-09-14               196
36           financial_services              4201
37                fs_2017-05-22               396
38                          gpl                16
39              integrator_arm7                33
40                          lcm                 6
41  soletta_2015-06-26_18-38-56                24
42   toybox_2006-10-31_23-30-06                 8
43   toybox_2020-12-06_00-02-46                 7
44   uclibc_2008-06-05_13-46-47               505
45   uclibc_2020-12-24_11-54-53               365

In [9]:
baseline_gap_data = baseline_data.merge(lower_bound_data, on="instance_name", how="right")
baseline_gap_data["gap"] = 100*( 1- (baseline_gap_data["best_lower_bound"]/ baseline_gap_data["sample_size"]))
baseline_gap_data

,instance_name,num_vars,num_clauses,baseline_alg,baseline_alg_conf,Time,sample_size,path_to_baseline_sample,best_lower_bound,gap
0,APL,23.0,35.0,ACTS-IPOG-FT,t2,550.0,11.0,results/2023-07-16_22-29-39/9_1_0_1_sample.csv,7,36.363636
1,APL,23.0,35.0,ACTS-IPOG-CSP,t2,1220.0,11.0,results/2023-07-16_22-29-39/9_1_1_1_sample.csv,7,36.363636
2,APL,23.0,35.0,ACTS-IPOF-FT,t2,585.0,10.0,results/2023-07-16_22-29-39/9_1_2_1_sample.csv,7,30.000000
3,APL,23.0,35.0,ACTS-IPOF-CSP,t2,1191.0,10.0,results/2023-07-16_22-29-39/9_1_3_1_sample.csv,7,30.000000
4,APL-Model,28.0,40.0,ACTS-IPOG-FT,t2,619.0,15.0,results/2023-07-16_22-29-39/11_1_0_1_sample.csv,7,53.333333
...,...,...,...,...,...,...,...,...,...,...
137,soletta_2015-06-26_18-38-56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24,NaN
138,toybox_2006-10-31_23-30-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN
139,toybox_2020-12-06_00-02-46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,NaN
140,uclibc_2008-06-05_13-46-47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,505,NaN
141,uclibc_2020-12-24_11-54-53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,365,NaN

In [10]:
baseline_gap_data.to_json("./03_baseline_gap_data.json.zip")