In [7]:
from _utils import parse_solution_overview

baseline_data = parse_solution_overview("./00_baseline_data.zip")
baseline_data = baseline_data.drop_duplicates(subset=["Instance", "AlgorithmID", "AlgorithmIteration", "ModelID", "Settings"])
baseline_data.loc[baseline_data["Path"].isna(), "SampleSize"] = None
baseline_data = baseline_data[["Instance", "#Variables", "#Clauses", "Algorithm", "Settings", "Time", "SampleSize", "Path"]]
baseline_data.rename(columns={"Time": "runtime", "#Variables": "num_vars", "#Clauses": "num_clauses", "Instance": "instance_name", "Path": "path_to_baseline_sample", "Algorithm": "baseline_alg", "Settings": "baseline_alg_conf", "SampleSize": "sample_size"}, inplace=True)
baseline_data.to_json("./03_simple_baseline_data.json.zip")
baseline_data

Found the data folders: {'results/2023-07-16_22-29-39/'}

,instance_name,num_vars,num_clauses,baseline_alg,baseline_alg_conf,runtime,sample_size,path_to_baseline_sample
0,calculate,9,15,ACTS-IPOG-FT,t2,878,9.0,results/2023-07-16_22-29-39/1_1_0_1_sample.csv
1,lcm,9,16,ACTS-IPOG-FT,t2,484,9.0,results/2023-07-16_22-29-39/2_1_0_1_sample.csv
2,email,10,17,ACTS-IPOG-FT,t2,478,8.0,results/2023-07-16_22-29-39/3_1_0_1_sample.csv
3,ChatClient,14,20,ACTS-IPOG-FT,t2,509,10.0,results/2023-07-16_22-29-39/4_1_0_1_sample.csv
4,car,16,33,ACTS-IPOG-FT,t2,556,6.0,results/2023-07-16_22-29-39/5_1_0_1_sample.csv
...,...,...,...,...,...,...,...,...
507,m5272c3,1336,3111,ACTS-IPOF-CSP,t2,900030,NaN,None
508,sam7ex256,1345,3155,ACTS-IPOF-CSP,t2,900028,NaN,None
509,phycore229x,1373,3185,ACTS-IPOF-CSP,t2,900032,NaN,None
510,FreeBSD-8_0_0,1397,15692,ACTS-IPOF-CSP,t2,900009,NaN,None
511,ea2468,1408,3319,ACTS-IPOF-CSP,t2,900037,NaN,None

In [8]:
print(baseline_data["instance_name"].nunique())
baseline_data["instance_name"].unique()

128

array(['calculate', 'lcm', 'email', 'ChatClient', 'car', 'FeatureIDE',
       'FameDB2', 'FameDB', 'APL', 'SafeBali', 'APL-Model', 'gpl', 'dell',
       'PPU', 'fiasco', 'berkeleyDB1', 'axTLS', 'berkeleyDB2',
       'BattleofTanks', 'BankingSoftware', 'eShopSplot', 'E-Shop',
       'eShopFIDE', 'DMIE', 'fs_2017-05-22', 'financial_services',
       'busybox-1_18_0', 'busybox-1_23_1', 'busybox-1_29_2', 'am31_sim',
       'EMBToolkit', 'calm16_ceb', 'calm32_ceb', 'psim', 'h8300h_sim',
       'h8s_sim', 'fads', 'ceb_v850', 'edosk2674', 'jmr3904', 'h8max',
       'cma28x', 'aki3068net', 'atlas_mips64_5kc', 'cma230', 'mpc50',
       'gps4020', 'aeb', 'atlas_mips32_4kc', 'ref4955', 'brutus',
       'sa1100mm', 'prpmc1100', 'pid', 'mb93093', 'asb',
       'malta_mips64_5kc', 'malta_mips32_4kc', 'eCos-3-0_i386pc',
       'csb281', 'eb42', 'mac7100evb', 'mace1', 'excalibur_arm9',
       'frv400', 'cq7708', 'eb40', 'grg', 'eb40a', 'jtst', 'asb2305',
       'ebsa285', 'edb7xxx', 'ixdp425', 'pati', 'picasso', 'lpcmt',
       'p2106', 'mcb2100', 'mb93091', 'dreamcast', 'sh7708', 'pc_vmWare',
       'iq80321', 'innovator', 'pc_rltk8139', 'iq80310', 'npwr', 'ipaq',
       'pc_i82544', 'pc_i82559', 'integrator_arm7', 'sh4_202_md',
       'olpch2294', 'refidt334', 'aim711', 'nano', 'flexanet', 'ocelot',
       'cme555', 'assabet', 'e7t', 'ec555', 'cq7750', 'integrator_arm9',
       'eb55', 'adder', 'olpcl2294', 'phycore', 'olpce2294', 'cerf',
       'adderII', 'moab', 'pc_usb_d12', 'aaed2000', 'cerfpda', 'mbx',
       'se7751', 'at91sam7sek', 'hs7729pci', 'rattler', 'at91sam7xek',
       'se77x9', 'm5272c3', 'sam7ex256', 'phycore229x', 'FreeBSD-8_0_0',
       'ea2468'], dtype=object)

In [9]:
baseline_data

,instance_name,num_vars,num_clauses,baseline_alg,baseline_alg_conf,runtime,sample_size,path_to_baseline_sample
0,calculate,9,15,ACTS-IPOG-FT,t2,878,9.0,results/2023-07-16_22-29-39/1_1_0_1_sample.csv
1,lcm,9,16,ACTS-IPOG-FT,t2,484,9.0,results/2023-07-16_22-29-39/2_1_0_1_sample.csv
2,email,10,17,ACTS-IPOG-FT,t2,478,8.0,results/2023-07-16_22-29-39/3_1_0_1_sample.csv
3,ChatClient,14,20,ACTS-IPOG-FT,t2,509,10.0,results/2023-07-16_22-29-39/4_1_0_1_sample.csv
4,car,16,33,ACTS-IPOG-FT,t2,556,6.0,results/2023-07-16_22-29-39/5_1_0_1_sample.csv
...,...,...,...,...,...,...,...,...
507,m5272c3,1336,3111,ACTS-IPOF-CSP,t2,900030,NaN,None
508,sam7ex256,1345,3155,ACTS-IPOF-CSP,t2,900028,NaN,None
509,phycore229x,1373,3185,ACTS-IPOF-CSP,t2,900032,NaN,None
510,FreeBSD-8_0_0,1397,15692,ACTS-IPOF-CSP,t2,900009,NaN,None
511,ea2468,1408,3319,ACTS-IPOF-CSP,t2,900037,NaN,None

In [11]:
baseline_data.to_json("./03_simple_baseline_data.json.zip")